### ISSUE TITLE
Don't use immediate force unwrap on `discovery`

### ISSUE THREAD

**Issue by sindresorhus** [exPHAT/SwiftBluetooth#8]
This crashes in some situations: https://github.com/exPHAT/SwiftBluetooth/blob/c5a9f4e5d6d1ffc312ffe26ea1760dc9a9a9673f/Sources/SwiftBluetooth/Peripheral/Peripheral.swift#L31C30-L31C39

When retrieving the device from `central.retrievePeripherals(withIdentifiers: [uuid])`.

**Comment by exPHAT** [comment]
This should be fixed in the #3 merge yesterday with a commit that was added last minute. The crash would happen if you `connect -> disconnect -> central.retrievePeripherals()`. I've [added a test case](https://github.com/exPHAT/SwiftBluetooth/commit/82395b9717df77621e080d8e38b74464ad02826d) to confirm it's fixed for now.

Feels wrong to even have an implicitly-unwrapped Optional in the repo. I would like to remove it altogether. I don't see a scenario where you access a peripheral that wasn't first "discovered", meaning a standard Optional wouldn't be needed either. If that is true, I could add the `Peripheral.discovery` to the initializer but it would force that same assumption on all delegate methods that will need to wrap a `CBPeripheral -> Peripheral`.

If you have any input, I'm open to it!
